In [110]:
# seven_df
#위도경도받아보기
# seven_df.shape
# seven_df.head(3)
# seven_df.columns=["store_name","store_address","store_service"]
# seven_df[seven_df["store_name"].duplicated()].sum()
# seven_df[seven_df["store_name"].duplicated()].head(3)
# seven_df[seven_df.store_name=="가운주공점"]
# seven_df.store_service.loc[0]
# unique_seven = seven_df[~seven_df["store_name"].duplicated()].copy()
# unique_seven.shape
# unique_seven.isnull().sum() 
# unique_seven['sido'] = unique_seven.store_address.apply(lambda x : x.split()[0]) #첫번째값 가져오기 
# unique_seven.value_counts('sido')
# service_set=set()
# unique_seven['store_service'].apply(lambda x : [service_set.add(y) for y in x])
#패턴잡기
# unique_seven["24시간"]= unique_seven.store_service.apply(lambda x : True if "24시간" in x else False)
# unique_seven.value_counts('24시간',normalize=True)
# for service in service_set:
    # print(x)
    # unique_seven[service]= unique_seven.store_service.apply(lambda x : True if service in x else False)
# unique_seven.drop(['store_service'],axis=1,inplace=True)
# unique_seven
# pip install sqlalchemy
# 세븐일레븐 db넣어보기
# import sqlalchemy #orm 써봤다, 장고나 플라스크할때 alchemy로 스키마작성안해도 알아서넣어준다 
#dbeaver
# from urllib import parse
# user = 'id'
# password = 'pw'
# host='ip'
# port = 3306
# database = 'encore'
# password = parse.quote_plus(password)
# engine = sqlalchemy.create_engine(f"mysql://{user}:{password}@{host}:{port}/{database}")
# unique_seven.to_sql('seven',index=False,if_exists="append",con=engine)

In [112]:
import pickle
import pandas as pd
import numpy as np
with open("./seven_stores.pkl","rb") as f:
    seven_df= pickle.load(f)

In [113]:
tmp = set()
seven_df.able_services.apply(lambda x : [tmp.add(y) for y in x])

0                                 [None, None, None, None]
1                                             [None, None]
2                     [None, None, None, None, None, None]
3                                             [None, None]
4                                       [None, None, None]
                               ...
12867                                         [None, None]
12868                                         [None, None]
12869    [None, None, None, None, None, None, None, Non...
12870                                         [None, None]
12871                                         [None, None]
Name: able_services, Length: 12872, dtype: object

In [114]:
seven_df.able_services.apply(lambda x : 1 if "24시간" in x else 0)

0        0
1        0
2        1
3        0
4        0
        ..
12867    0
12868    0
12869    1
12870    0
12871    0
Name: able_services, Length: 12872, dtype: int64

In [115]:
#hardcoding

In [116]:
for service in tmp:
    seven_df[service] = seven_df.able_services.apply(lambda x : 1 if service in x else 0)

In [117]:
seven_df.의약품.sum() #값이 0 과 1로 되어있으므로 sum해도 된다

4988

In [118]:
#비율 보고싶을때
seven_df.의약품.value_counts(normalize=True)

의약품
0    0.612492
1    0.387508
Name: proportion, dtype: float64

In [119]:
seven_df.drop(["able_services"],axis=1,inplace=True) #inplace하기전에 해도 괜찮은지 확인하기

In [120]:
seven_df.shape

(12872, 17)

In [121]:
seven_df.drop_duplicates().shape

(12417, 17)

In [122]:
seven_df.drop_duplicates(inplace=True)

In [123]:
seven_df = seven_df[~seven_df.name.duplicated()].copy()

In [124]:
seven_df.head(3)

,name,address,의약품,시디,토토,24시간,예약주문,치킨,소프트아이스크림,무인락커,스마트픽,ATM,카페,페덱스서비스,무인택배접수,베이커리,고구마·붕어빵
0,강릉5주공점,강원도 강릉시 월대산로 43,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0
1,강릉강문스타점,강원도 강릉시 창해로350번길 21 (강문동),0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
2,강릉강문점,"강원도 강릉시 해안로 298-7 B블록 101호, 102호(강문동)",1,0,0,1,0,0,0,0,1,0,1,1,1,0,0

In [125]:
seven_df['sido']=seven_df.address.apply(lambda x : x.split()[0])

In [126]:
seven_df["address"].apply(lambda x : x.split()[0]).unique()

array(['강원도', '강원특별자치도', '강원', '경기도', '경기', '경기도김포시하성면하성로297',
       '경기도시흥시복지로', '경기도이천시부발읍', '경상남도', '경남', '경남창원시', '경상북도', '경북',
       '경상북도영주시광복로', '광주광역시', '광주', '광주동구제봉로222번길', '대구광역시', '대구', '대구남구',
       '대구시달서구월배로', '대구광역시달서구상인서로', '대구달서구', '대구광역시달서구달구벌대로', '대구시',
       '대구시달성군', '대전광역시', '대전', '대전시', '대전광영시', '대전광역시유성구대학로137번길',
       '부산광역시', '부산시', '부산', '서울특별시', '서울', '서울시', '서울특별실', '서울동대문구',
       '서울트별시', '주소', '서울특별시송파구송파대로345송파헬리오시티', '울산광역시', '울산', '인천광역시',
       '인천시', '인천', '전라남도', '전남', '전라북도', '전북', '전북특별자치도', '전라북도전주시',
       '제주특별자치도', '제주', '제주도', '제주특별자치도서귀포시', '제주특별시도', '충남', '충청남도',
       '충남논산시', '충청북도', '충북'], dtype=object)

In [127]:
pd.set_option('display.max_rows',100)

In [128]:
seven_df.loc[seven_df['sido'].str.find("서울")>-1,"sido"]="서울특별시"

In [129]:
# seven_df['sido'].value_counts()

In [130]:
seven_df.sido.unique().size

57

In [131]:
import requests 
r = requests.post("https://www.7-eleven.co.kr/util/storeLayerPop.asp")
from bs4 import BeautifulSoup
sido_name = [x.text for x in BeautifulSoup(r.text).find("select", id="storeLaySido").findAll('option')[1:]]

In [132]:
sido_name.__len__()

17

In [133]:
change_dict = {'서울':"서울특별시", '경기':"경기도", '인천':"인천광역시", '강원':"강원도", '충북':"충청북도", '충남':"충청남도", '대전':"대전광역시", '경북':"경상북도", '경남':"경상남도", '대구':"대구광역시", '울산':"울산광역시", '부산':"부산광역시", '전북':"전라북도", '전남':"전라남도", '광주':"광주광역시", '제주':"제주특별자치도", '세종':"세종특별자치시"}

for key, value in change_dict.items():
  seven_df['sido'] = seven_df['sido'].apply(lambda x: value if key in x else x)

In [134]:
seven_df["sido"].value_counts() #전처리잘하기

sido
경기도           3401
서울특별시         2046
경상남도           671
충청남도           665
경상북도           604
인천광역시          600
대구광역시          582
부산광역시          580
강원도            569
충청북도           501
전라남도           492
전라북도           438
광주광역시          394
대전광역시          350
제주특별자치도        300
울산광역시          220
전라북도전주시          2
주소               1
경상북도영주시광복로       1
Name: count, dtype: int64

In [135]:
seven_df.loc[seven_df.sido == '주소', 'address'] = "서울시 서대문구 충정로7 구세군빌딩1층"
seven_df.loc[seven_df.sido == '주소', 'sido'] = "서울특별시"

In [137]:
seven_df.loc[seven_df.sido == '전라북도전주시', 'sido'] = "전라북도"
seven_df.loc[seven_df.sido == '경상북도영주시광복로', 'sido'] = "경상북도"
seven_df['sido'].value_counts()

sido
경기도        3401
서울특별시      2047
경상남도        671
충청남도        665
경상북도        605
인천광역시       600
대구광역시       582
부산광역시       580
강원도         569
충청북도        501
전라남도        492
전라북도        440
광주광역시       394
대전광역시       350
제주특별자치도     300
울산광역시       220
Name: count, dtype: int64

In [ ]:
# seven_df[seven_df.name.str.find("세종봉암중앙점")>-1]

In [141]:
seven_df['company']="seven"

In [142]:
seven_df #pd.concat

,name,address,의약품,시디,토토,24시간,예약주문,치킨,소프트아이스크림,무인락커,스마트픽,ATM,카페,페덱스서비스,무인택배접수,베이커리,고구마·붕어빵,sido,company
0,강릉5주공점,강원도 강릉시 월대산로 43,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,강원도,seven
1,강릉강문스타점,강원도 강릉시 창해로350번길 21 (강문동),0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,강원도,seven
2,강릉강문점,"강원도 강릉시 해안로 298-7 B블록 101호, 102호(강문동)",1,0,0,1,0,0,0,0,1,0,1,1,1,0,0,강원도,seven
3,강릉강변로점,강원도 강릉시 강변로 262,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,강원도,seven
4,강릉경포그린점,"강원도 강릉시 경포로463번길 37, 제2호",0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,강원도,seven
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12867,충주터미널점,충청북도 충주시 봉계1길 49,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,충청북도,seven
12868,충주푸르지오점,"충청북도 충주시 봉계8길 2 , 1층",0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,충청북도,seven
12869,충주호암점,충청북도 충주시 호암중앙2로 32 101호(호암동),1,1,0,1,1,1,0,0,1,0,1,1,1,0,0,충청북도,seven
12870,충주호암LH점,충청북도 충주시 호암수청2로 56,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,충청북도,seven
12871,충주힐스테이트점,"충청북도 충주시 호암수청1로 29 (호암동, LH힐스테이트)",0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,충청북도,seven

In [143]:
seven_df.columns

Index(['name', 'address', '의약품', '시디', '토토', '24시간', '예약주문', '치킨', '소프트아이스크림',
       '무인락커', '스마트픽', 'ATM', '카페', '페덱스서비스', '무인택배접수', '베이커리', '고구마·붕어빵',
       'sido', 'company'],
      dtype='object')

In [144]:
seven_df = seven_df[['company', 'name', 'sido', 'address', '24시간', '무인택배접수', '카페', '베이커리', '시디', 'ATM', '무인락커',
       '치킨', '의약품', '소프트아이스크림', '토토', '고구마·붕어빵', '스마트픽', '예약주문', '페덱스서비스',
        ]].copy()

,company,name,sido,address,24시간,무인택배접수,카페,베이커리,시디,ATM,무인락커,치킨,의약품,소프트아이스크림,토토,고구마·붕어빵,스마트픽,예약주문,페덱스서비스
0,seven,강릉5주공점,강원도,강원도 강릉시 월대산로 43,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1
1,seven,강릉강문스타점,강원도,강원도 강릉시 창해로350번길 21 (강문동),0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2,seven,강릉강문점,강원도,"강원도 강릉시 해안로 298-7 B블록 101호, 102호(강문동)",1,1,1,0,0,0,0,0,1,0,0,0,1,0,1
3,seven,강릉강변로점,강원도,강원도 강릉시 강변로 262,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
4,seven,강릉경포그린점,강원도,"강원도 강릉시 경포로463번길 37, 제2호",0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12867,seven,충주터미널점,충청북도,충청북도 충주시 봉계1길 49,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
12868,seven,충주푸르지오점,충청북도,"충청북도 충주시 봉계8길 2 , 1층",0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
12869,seven,충주호암점,충청북도,충청북도 충주시 호암중앙2로 32 101호(호암동),1,1,1,0,1,0,0,1,1,0,0,0,1,1,1
12870,seven,충주호암LH점,충청북도,충청북도 충주시 호암수청2로 56,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
12871,seven,충주힐스테이트점,충청북도,"충청북도 충주시 호암수청1로 29 (호암동, LH힐스테이트)",0,1,0,0,0,0,0,0,0,0,0,0,0,0,1

In [146]:
# pd.melt(seven_df,id_vars=["
seven_melt = pd.melt(seven_df, id_vars=['company', 'name', 'sido', 'address'])

In [147]:
seven_melt

,company,name,sido,address,variable,value
0,seven,강릉5주공점,강원도,강원도 강릉시 월대산로 43,24시간,0
1,seven,강릉강문스타점,강원도,강원도 강릉시 창해로350번길 21 (강문동),24시간,0
2,seven,강릉강문점,강원도,"강원도 강릉시 해안로 298-7 B블록 101호, 102호(강문동)",24시간,1
3,seven,강릉강변로점,강원도,강원도 강릉시 강변로 262,24시간,0
4,seven,강릉경포그린점,강원도,"강원도 강릉시 경포로463번길 37, 제2호",24시간,0
...,...,...,...,...,...,...
186250,seven,충주터미널점,충청북도,충청북도 충주시 봉계1길 49,페덱스서비스,1
186251,seven,충주푸르지오점,충청북도,"충청북도 충주시 봉계8길 2 , 1층",페덱스서비스,1
186252,seven,충주호암점,충청북도,충청북도 충주시 호암중앙2로 32 101호(호암동),페덱스서비스,1
186253,seven,충주호암LH점,충청북도,충청북도 충주시 호암수청2로 56,페덱스서비스,1
186254,seven,충주힐스테이트점,충청북도,"충청북도 충주시 호암수청1로 29 (호암동, LH힐스테이트)",페덱스서비스,1

In [ ]:
#멜트타운

In [148]:
seven_melt.columns

Index(['company', 'name', 'sido', 'address', 'variable', 'value'], dtype='object')

In [149]:
seven_melt.rename(columns={"variable" : "service_name"},inplace=True)